# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_remove_video_album_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='video',
            name='genre',
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_link',
            field=models.URLField(default=0),
        ),
    ]
