# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20170120_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField()),
                ('VideoId', models.CharField(max_length=50)),
                ('TS', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
