# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_auto_20170211_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='Rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
