# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_auto_20170212_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=2000)),
                ('image_url', models.CharField(max_length=2000)),
                ('duration', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=2000)),
            ],
        ),
    ]
