# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_youtubevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
