# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_auto_20170308_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField()),
                ('VideoId', models.CharField(max_length=50)),
                ('Record', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='recording',
            unique_together=set([('UserId', 'VideoId')]),
        ),
    ]
