# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0010_auto_20170407_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='Record',
            field=models.FileField(upload_to='records/%Y/%m/%d'),
        ),
    ]
