# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0011_auto_20170407_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixationPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField()),
                ('VideoId', models.CharField(max_length=50)),
                ('PosX', models.IntegerField()),
                ('PosY', models.IntegerField()),
                ('StartTime', models.IntegerField()),
                ('Duration', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Recording',
        ),
        migrations.AlterUniqueTogether(
            name='fixationpoints',
            unique_together=set([('UserId', 'VideoId', 'StartTime')]),
        ),
    ]
