# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0013_auto_20170415_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userssim',
            name='Sim',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='usersvideosim',
            name='Sim',
            field=models.FloatField(),
        ),
    ]
