# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0016_auto_20170417_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoaverages',
            old_name='AvgFixCount',
            new_name='FixCount',
        ),
        migrations.RenameField(
            model_name='videoaverages',
            old_name='AvgFixDur',
            new_name='FixDur',
        ),
        migrations.RenameField(
            model_name='videoaverages',
            old_name='Count',
            new_name='UserID',
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='avg_fix_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='avg_fix_dur',
            field=models.FloatField(default=0),
        ),
    ]
